### ISSUE TITLE
PHP 8.1 compatibility / strptime() Deprecated Warning

### ISSUE THREAD

**Issue by ghohmann** [opencultureconsulting/simple-oai-pmh#14]
Hi,
another PHP 8.1 compatibility issue.

Calling `?verb=ListRecords&metadataPrefix=oai_dc` triggers following warning:
`Deprecated:  Function strptime() is deprecated in ./Classes/Server.php on line 280.`

Since PHP 8.1., function `strptime()` is deprecated and should be replaced with `date_parse_from_format`. See
https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.date

Didn't have the time to come up with a quick fix ...

**Comment by sebastian-meyer** [comment]
See my comment in #13 which also applies to this issue.
